template:
  - light:
      - name: "Main light"
        unique_id: main_light
        level: "{{ (states('input_number.light_slider') | float / 100 * 255) | int }}"
        turn_on:
          - action: input_number.set_value
            data:
              entity_id: input_number.light_slider
              value: 100
        turn_off:
          - action: input_number.set_value
            data:
              entity_id: input_number.light_slider
              value: 0
        set_level:
          - action: input_number.set_value
            data:
              entity_id: input_number.light_slider
              value: "{{ (brightness / 255 * 100)|int }}"
