name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: "0 12 23-31,1 * 4"  # The day after the beta release

jobs:

  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          cancel_others: 'true'
          concurrent_skipping: 'same_content_newer'
          paths_ignore: '[ "**/README.md", "**/CHANGELOG.md" ]'
          skip_after_successful_duplicate: 'true'

  test:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    timeout-minutes: 40
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Connect to the runner with ssh for debugging
    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1

    - name: Spin up containers
      env:
        DOCKER_BUILDKIT: 1
        BUILDKIT_PROGRESS: plain
      run: docker compose -f docker-compose.yml -f docker-compose.test.yml up --exit-code-from tester

    - name: Stop containers
      if: always()
      run: docker compose -f docker-compose.yml -f docker-compose.test.yml down

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        if-no-files-found: ignore
        retention-days: 7

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
